### ISSUE TITLE
Not able to see celltypes after processing the multimodal data with the multimodal run

### ISSUE THREAD

**Issue by ashishjain1988** [haniffalab/webatlas-pipeline#139]
Hi,

I am currently trying to combine my processed Visium and scRNAseq data using the multimodal run. Following the tutorial I was able to process the data and was able to see the combine feature (Gene list) but I am not able to see the combined cell type on webatlas-portal. Here is my multimodal config file that I used to process the data.
![image](https://github.com/user-attachments/assets/6cbc9de1-cd30-44f0-b69b-c611013b5995)

url: http://localhost:3000/p262_Multimodal_1/0.5.2/
project: p262_Multimodal
title: "Gut data"
description: ""
outdir: ./output/P262_Multimodal_1

data:
  - dataset: scrnaseq_demo
    obs_type: "cell"
    anndata: ./p262_output/0.5.2/p262-scRNAseq-anndata.zarr/
    extend_feature: obs/cell.idents.L1
    offset: 0
    is_spatial: false
    vitessce_options:
      spatial:
        xy: "obsm/spatial"
      mappings:
        obsm/X_umap: [0, 1]
      matrix: "X"
  - dataset: visium_demo
    obs_type: "spot"
    anndata: ./output/T604_WebAtlas_h5ad/0.5.2/visium-heart-disease-anndata.zarr/
    extend_feature: obs/RCTD_Prediction
    offset: 1000000
    is_spatial: true
    raw_image: ./output/T604_WebAtlas_h5ad/0.5.2/visium-heart-disease-raw.zarr/
    label_image: ./output/T604_WebAtlas_h5ad/0.5.2/visium-heart-disease-label.zarr/
    vitessce_options:
      spatial:
        xy: "obsm/spatial"
      matrix: "X"

I also tried to rename the cell annotations an try to use **extend_feature_name** but then I was not able to see even the overlapped gene list. Can you please help me to fix this?

Regards,
Ashish Jain

**Comment by ashishjain1988** [comment]
Hi @BioinfoTongLI and @dannda 

I would really appreciate your input on this issue that I am facing while working on the multi-omics processing webatlas pipeline.

**Comment by Zhuang-Bio** [comment]
I also met this problem when running the multimodal to combine multiple sections of 10X visum data. Have you tried to set the sort to False?
`extend_feature:  

      path: ./input/STseq_scanpy_cleanSpots_allData.h5ad
      args:
        sample: ["library_id", "Donor2_Wound1"]
        sort: False # If this is True, the deconvoluted cell type will not been loaded. A bit Weired.`

**Comment by ashishjain1988** [comment]
Hi @Zhuang-Bio 

Thank you for the suggestion. I am trying it but now my params file is not able to parse. I don't have a cell2location file for spot annotation but I did add a new metadata with the spot annotation as "RCTD_Prediction". Below is the new multi modal config file that was not able to parse. Thank you for your help!

```
url: http://localhost:3000/p262_Multimodal_1/0.5.2/
project: p262_Multimodal
title: "Gut data"
description: ""
outdir: ./output/P262_Multimodal_1

data:
  - dataset: scrnaseq_demo
    obs_type: "cell"
    anndata: ./p262_output/0.5.2/p262-scRNAseq-anndata.zarr/
    extend_feature: obs/cell.idents.L1
      args:
        sort: False
    offset: 0
    is_spatial: false
    vitessce_options:
      spatial:
        xy: "obsm/spatial"
      mappings:
        obsm/X_umap: [0, 1]
      matrix: "X"
  - dataset: visium_demo
    obs_type: "spot"
    anndata: ./output/T604_WebAtlas_h5ad/0.5.2/visium-heart-disease-anndata.zarr/
    extend_feature: obs/RCTD_Prediction
      args:
        sort: False
    offset: 1000000
    is_spatial: true
    raw_image: ./output/T604_WebAtlas_h5ad/0.5.2/visium-heart-disease-raw.zarr/
    label_image: ./output/T604_WebAtlas_h5ad/0.5.2/visium-heart-disease-label.zarr/
    vitessce_options:
      spatial:
        xy: "obsm/spatial"
      matrix: "X"
```
